# Generated by Django 3.1.2 on 2020-10-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='ass',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
